import type { AppData } from "./types";

export const REP = {
  name: "Anika Rao",
  role: "Relationship Manager",
  territory: "Bengaluru South",
  tenant: "Northstar Finance",
};

export const seedData = (): AppData => ({
  offline: false,
  leads: [
    {
      id: "kavya",
      name: "Kavya Sharma",
      company: "BrightPath Academy",
      role: "Admissions lead",
      phone: "+91 98450 11220",
      area: "Koramangala",
      address: "18, 80 Feet Road, Koramangala 4th Block",
      stage: "Qualified",
      product: "Education loan desk",
      valueLabel: "₹40 lakh pipeline",
    },
    {
      id: "rohan",
      name: "Rohan Desai",
      company: "Apex Motors",
      role: "Dealer principal",
      phone: "+91 98860 44118",
      area: "Indiranagar",
      address: "42, 100 Feet Road, Indiranagar",
      stage: "Proposal",
      product: "Dealer vehicle finance",
      valueLabel: "₹12 lakh line",
    },
    {
      id: "neha",
      name: "Neha Mehta",
      company: "Mehta Distributors",
      role: "Proprietor",
      phone: "+91 97411 22008",
      area: "Whitefield",
      address: "Plot 7, EPIP Zone, Whitefield",
      stage: "Visit scheduled",
      product: "DSA channel onboarding",
      valueLabel: "20 DSAs",
    },
    {
      id: "iyer",
      name: "Dr. Arun Iyer",
      company: "Iyer Clinic",
      role: "Founder",
      phone: "+91 99000 31844",
      area: "HSR Layout",
      address: "2nd Floor, 27th Main, HSR Layout",
      stage: "New",
      product: "Medical equipment loan",
      valueLabel: "₹18 lakh",
    },
    {
      id: "vikram",
      name: "Vikram Shah",
      company: "Apex Logistics",
      role: "Owner",
      phone: "+91 98111 67002",
      area: "Hebbal",
      address: "Warehouse 3, Hebbal Flyover Road",
      stage: "New",
      product: "Fleet working capital",
      valueLabel: "₹60 lakh",
    },
  ],
  visits: [
    { id: "v1", leadId: "kavya", time: "10:15", distanceKm: 0, status: "completed" },
    { id: "v2", leadId: "rohan", time: "11:40", distanceKm: 4.2, status: "upcoming" },
    { id: "v3", leadId: "neha", time: "13:30", distanceKm: 11.8, status: "upcoming" },
    { id: "v4", leadId: "iyer", time: "16:00", distanceKm: 6.1, status: "upcoming" },
  ],
  activities: [
    {
      id: "a1",
      leadId: "kavya",
      title: "Visit · BrightPath Academy",
      detail: "Discussed a counsellor desk for education loans. Kavya wants the rate card before the Friday admission fair.",
      at: "2026-09-23T10:40:00+05:30",
      source: "manual",
      synced: true,
    },
  ],
  tasks: [
    {
      id: "t1",
      leadId: "kavya",
      title: "Send the education-loan rate card",
      dueAt: "2026-09-23T18:00:00+05:30",
      done: false,
      source: "manual",
      synced: true,
    },
  ],
  audit: [],
});
